import { type NextPage } from "next"
import Head from "next/head";
import { useRouter } from "next/router";
import { useMemo } from "react";
import NavBar from "~/components/NavBar";
import { RepositoryMetadata } from "~/server/api/routers/example";

import { api } from "~/utils/api";

const Search: NextPage = () => {
  const router = useRouter()
  const text = typeof router.query.q === 'string' ? router.query.q : ''
  const { isLoading, error, data } = api.example.search.useQuery({ text });

  const parsedItems = useMemo(() => {
    return data?.items.map(({
      full_name,
      html_url,
      language,
      description,
      owner,
    }: RepositoryMetadata) => ({
      full_name,
      html_url,
      language,
      description,
      avatar_url: owner.avatar_url
    })) || []
  }, [data])


  return (
    <>
      <Head>
        <title>Searching for {text}</title>
        <meta name="description" content="generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        {isLoading && <div className="text-2xl text-white">Loading...</div>}
        {error && <pre className="text-sm text-white">{JSON.stringify(error, [0], 2)}</pre>}
        {data && (
          <div className="p-10">
            <div>Total Count:{data.total_count}{'...' && data.incomplete_results}</div>
            {/* <pre className="text-sm text-white">{JSON.stringify(data.items, 0 ,2)}</pre> */}
            {
              parsedItems.map(({
                full_name,
                html_url,
                language,
                description,
                avatar_url
              }) => (
                <div key={full_name} className="flex flex-col my-10">
                  <img className="w-20" src={avatar_url} alt="baba" />
                  <div>{full_name}</div>
                  <a href={html_url}>{html_url}</a>
                  <div>{language}</div>
                  <p>{description}</p>
                </div>
              ))
            }
          </div>
        )}
      </main>
    </>
  );
};

export default Search;
